### ISSUE TITLE
Plugin stores config file in wrong folder

### ISSUE THREAD

**Issue by dinkumoil** [SinghRajenM/nppURLPlugin#1]
Actually, this is a two-part issue, but both parts can be fixed with the same change.

1. When the plugin is used in a portable version of _Notepad++_ it nevertheless stores its config file in the location of an installed version of _Notepad++_ (i.e. the user profile of the user currently running _Notepad++_).
2. The plugin creates the folder for its config file under `plugins` instead of `plugins\config`.

I guess both issues can be fixed by using `NPPM_GETPLUGINSCONFIGDIR` API.

**Comment by SinghRajenM** [comment]
Thanks for testing and reporting it. I will look into it.
