### ISSUE TITLE
Crashes Notepad++ 8.3.3 64bit

### ISSUE THREAD

**Issue by tolleif** [SinghRajenM/nppURLPlugin#4]
url plugin v 1.1.0.0
Copy the string below to a blank notepad doc.
https://wiki.somedomain.com/labels/viewlabel.action?key=en&ids=1234&ids=56789

Select the line above

Menu -> Plugins -> URL Plugin > Decode URL 

2 seconds and Notepadd++ window and process is terminated.

Same happens for Encode URL.

**Comment by SinghRajenM** [comment]
Underlying scintilla component has been  updated in notepad++ v8.3.3.0 which introduced some interface changes too. Hence, this crash.

We have upgraded the plugin too to v1.2.0.0. This version will be available in next plugin admin update. Meanwhile you can manually download and update it from below location - 

https://github.com/SinghRajenM/nppURLPlugin/releases/tag/1.2.0.0.

## Steps to update manually
1. Download the appropriate binay zip file from above link.
2. extract the zip file to some local firectory
3. Copy `urlPlugin.dll` to `C:\Program Files\Notepad++\plugins\urlPlugin` or `C:\Program Files (x86)\Notepad++\plugins\urlPlugin` as appropriate.

**Comment by tolleif** [comment]
I tested it and it worked!
Great response and work. 
Thanks Rajendra.

Best regards,
Tolleif
