### ISSUE TITLE
Using plugin Shuts down Notepad++

### ISSUE THREAD

**Issue by jillpapendick** [SinghRajenM/nppURLPlugin#6]
I used this a couple of weeks ago and now when I click on it, Notepad_++ shuts down when I try to encode a file.  I think there was a NotePad++ installed after the last time this worked successfully about 3 weeks ago.

**Comment by SinghRajenM** [comment]
@jillpapendick could you please -
1. Notepad++ version 
2. URL plugin version 

#### To get Notepad++ version
1. Click on menu `?` -> "Debug Info"
2. "Copy debug into in clipboard" and paste here

#### To get URL plugin version 
1. Click on menu "Plugins -> URL Plugin -> About"
2. Take the screenshot and paste it here.

**Comment by yokonzo** [comment]
Same issue N++ version: v8.3.3

Plugin version 1.1.0.0

N++ closes as soon as decode is hit, it's done on a very big file, perhaps is an overflow error?

**Comment by SinghRajenM** [comment]
@yokonzo 
I tried multiple time with different dataset. I am unable to reproduce it.
Would you mind sharing test data file to root cause the issue?

**Comment by jillpapendick** [comment]
Here’s the file.  I have updated my NotePad++ since I opened the ticket.  I tested with this file (which is totally masked) with the encode URL and NotePad ++ shut down.

**Comment by SinghRajenM** [comment]
@jillpapendick looks like you forgot to attach the file. Or the is high chance that Github does not allow to attach the file directly via email. Please try to attach to the Git URL directly.

**Comment by jillpapendick** [comment]
Here’s what is in the file.

{"zi":"TESTTENANT_DEV","cn":"JPsPostY","dt":"12","ci":"TESTTENANT_DEV~DKksJMxg1K2bb6vfPCwnFG-DvGrxb3IdWStZGc32uk1","cs":"ZZZ6WiswMA3o3J-4CaC0IeUmIKyfNvYBkRWXXqDBkgCVQ1BiZeyzM7-7KIkyCw4gdFRR3FN8q_Kbpr8SwuCRfg","iu":https://monster-ionapi.testcompany.com,"pu":https://monster-sso.testcompoany.com:443/TESTTENANT_DEV/as/,"oa":"authorization.oauth2","ot":"token.oauth2","or":"revoke_token.oauth2","sc":[],"ev":"U1478358101","v":"1.1","saak":"TESTTENANT_DEV#cBZKF4huKaYS_cewks5cwQsKzwcsl3x8kb0TztuolkoAjtXVE7bOTWwBXXeAjgqtwwjKA0V6Mc-4SLLEmQzIHw","sask":"zzz-ajE7FA1QL51jQTfCENKUj3K_o3H9lFgPyukcfKe4KDYiaCfOB5JMX3ASm-e8jXfXOrl4ISDxQFSz3YDFvA"}

**Comment by SinghRajenM** [comment]
@jillpapendick @yokonzo  I am able to reproduce the issue now, but it is only happening with V1.1.0.0. There is already a newer version available. This was happening due to ABI (Applicable Binary Interface) incompatibility.

Please update the URL plugin via `Plugin Admin`. To update it follow below steps - 
1. Open `Plugin Admin` from `Plugins` menu
2. Click on `Updates` tab.
3. Select URL Encode/Decode Plugin.
4. Click on `Update`

**Comment by jillpapendick** [comment]
Thank you so much,  it’s working now.

**Comment by yokonzo** [comment]
Can confirm it is working for me as well, thanks!
